// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YieldRaccoon.Infrastructure.Data.Context;


#nullable disable

namespace YieldRaccoon.Infrastructure.Migrations
{
    [DbContext(typeof(YieldRaccoonDbContext))]
    partial class YieldRaccoonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("CountryId");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("UX_Countries_DisplayName");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundCountryAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("FundCountryAllocationId");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CountryId");

                    b.Property<string>("IsinId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasColumnName("Isin")
                        .IsFixedLength();

                    b.Property<decimal>("Percentage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IsinId", "CountryId")
                        .IsUnique()
                        .HasDatabaseName("UX_FundCountryAllocations_Isin_CountryId");

                    b.ToTable("FundCountryAllocations", (string)null);
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundHistoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Capital")
                        .HasColumnType("REAL");

                    b.Property<string>("IsinId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasColumnName("FundId")
                        .IsFixedLength();

                    b.Property<decimal?>("Nav")
                        .HasColumnType("REAL");

                    b.Property<DateOnly?>("NavDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfOwners")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Risk")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SharpeRatio")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IsinId", "NavDate")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("UX_FundHistoryRecords_FundId_NavDate");

                    b.ToTable("FundHistoryRecords", (string)null);
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasColumnName("Isin")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("AboutFundLastVisitedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Buyable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Capital")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CrawlerLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EnvironmentalScore")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("EsgScore")
                        .HasColumnType("REAL");

                    b.Property<string>("EuArticleType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GovernanceScore")
                        .HasColumnType("REAL");

                    b.Property<bool?>("HasCashDividends")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCurrencyExchangeFee")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsIndexFund")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LowCarbon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagedType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ManagementFee")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("MinimumBuy")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfOwners")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OngoingFee")
                        .HasColumnType("REAL");

                    b.Property<string>("OrderbookId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedHoldingPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Risk")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SharpeRatio")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("SocialScore")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.Property<DateOnly?>("StartDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SustainabilityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SustainabilityRating")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalFee")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("TransactionFee")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FundProfiles", (string)null);
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundSectorAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("FundSectorAllocationId");

                    b.Property<string>("IsinId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasColumnName("Isin")
                        .IsFixedLength();

                    b.Property<decimal>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SectorId");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("IsinId", "SectorId")
                        .IsUnique()
                        .HasDatabaseName("UX_FundSectorAllocations_Isin_SectorId");

                    b.ToTable("FundSectorAllocations", (string)null);
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("SectorId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("UX_Sectors_DisplayName");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundCountryAllocation", b =>
                {
                    b.HasOne("YieldRaccoon.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YieldRaccoon.Domain.Entities.FundProfile", null)
                        .WithMany()
                        .HasForeignKey("IsinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundHistoryRecord", b =>
                {
                    b.HasOne("YieldRaccoon.Domain.Entities.FundProfile", "FundProfile")
                        .WithMany("HistoryRecords")
                        .HasForeignKey("IsinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundProfile");
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundSectorAllocation", b =>
                {
                    b.HasOne("YieldRaccoon.Domain.Entities.FundProfile", null)
                        .WithMany()
                        .HasForeignKey("IsinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YieldRaccoon.Domain.Entities.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("YieldRaccoon.Domain.Entities.FundProfile", b =>
                {
                    b.Navigation("HistoryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
