using System.Diagnostics;
using YieldRaccoon.Domain.ValueObjects;

namespace YieldRaccoon.Domain.Entities;

/// <summary>
/// Entity representing a point-in-time historical record of fund data.
/// </summary>
/// <remarks>
/// <para>
/// Contains time-varying fund metrics captured during crawling: NAV, capital, risk indicators.
/// Each record is a snapshot for a specific date, belonging to the <see cref="FundProfile"/> aggregate.
/// </para>
/// <para>
/// Unique constraint: one record per fund per NAV date (FundId + NavDate).
/// </para>
/// </remarks>
[DebuggerDisplay("FundHistoryRecord: {IsinId} (Id: {Id})")]
public sealed class FundHistoryRecord
{
    /// <summary>
    /// Unique identifier for this history record. Auto-generated by the database.
    /// </summary>
    public FundHistoryRecordId Id { get; init; }

    /// <summary>
    /// Fund identifier (ISIN). Foreign key to <see cref="FundProfile"/>.
    /// </summary>
    public required IsinId IsinId { get; init; }

    /// <summary>
    /// Net asset value per share at the time of recording.
    /// </summary>
    public decimal? Nav { get; init; }

    /// <summary>
    /// Date when NAV was calculated. One NAV per fund per day.
    /// </summary>
    public DateOnly? NavDate { get; init; }

    /// <summary>
    /// Total assets under management in fund currency at the time of recording.
    /// </summary>
    public decimal? Capital { get; init; }

    /// <summary>
    /// Number of unique investors holding the fund at the time of recording.
    /// </summary>
    public int? NumberOfOwners { get; init; }

    /// <summary>
    /// Risk level (1-7, SRRI/SRI indicator) at the time of recording.
    /// </summary>
    public int? Risk { get; init; }

    /// <summary>
    /// Sharpe ratio (risk-adjusted return) at the time of recording.
    /// </summary>
    public decimal? SharpeRatio { get; init; }

    /// <summary>
    /// Standard deviation (annualized volatility) at the time of recording.
    /// </summary>
    public decimal? StandardDeviation { get; init; }

    /// <summary>
    /// Navigation property to parent fund profile.
    /// </summary>
    public FundProfile? FundProfile { get; init; }

    /// <inheritdoc />
    public override string ToString() => $"Record {Id} for {IsinId}";
}
