// <auto-generated />
using System;
using Backend.API.Infrastructure.FundData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.API.Infrastructure.FundData.Migrations
{
    [DbContext(typeof(FundDataDbContext))]
    [Migration("20260330164146_AddFundProfileDescription")]
    partial class AddFundProfileDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.API.Domain.FundData.Models.FundHistoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Capital")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("IsinId")
                        .IsRequired()
                        .HasColumnType("NCHAR(12)")
                        .HasColumnName("FundId")
                        .IsFixedLength();

                    b.Property<decimal?>("Nav")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<DateOnly?>("NavDate")
                        .HasColumnType("DATE");

                    b.Property<int?>("NumberOfOwners")
                        .HasColumnType("int");

                    b.Property<int?>("Risk")
                        .HasColumnType("int");

                    b.Property<decimal?>("SharpeRatio")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal?>("StandardDeviation")
                        .HasColumnType("DECIMAL(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("IsinId", "NavDate")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("UX_FundHistoryRecords_FundId_NavDate")
                        .HasFilter("[NavDate] IS NOT NULL");

                    b.ToTable("FundHistoryRecords", (string)null);
                });

            modelBuilder.Entity("Backend.API.Domain.FundData.Models.FundProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NCHAR(12)")
                        .HasColumnName("Isin")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("AboutFundLastVisitedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("Buyable")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Capital")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("CrawlerLastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("EnvironmentalScore")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal?>("EsgScore")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<string>("EuArticleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FundType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GovernanceScore")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<bool?>("HasCashDividends")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasCurrencyExchangeFee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIndexFund")
                        .HasColumnType("bit");

                    b.Property<bool?>("LowCarbon")
                        .HasColumnType("bit");

                    b.Property<string>("ManagedType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ManagementFee")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal?>("MinimumBuy")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NumberOfOwners")
                        .HasColumnType("int");

                    b.Property<decimal?>("OngoingFee")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<string>("OrderbookId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedHoldingPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Risk")
                        .HasColumnType("int");

                    b.Property<decimal?>("SharpeRatio")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal?>("SocialScore")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal?>("StandardDeviation")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("DATE");

                    b.Property<string>("SustainabilityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SustainabilityRating")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalFee")
                        .HasColumnType("DECIMAL(18,6)");

                    b.Property<decimal?>("TransactionFee")
                        .HasColumnType("DECIMAL(18,6)");

                    b.HasKey("Id");

                    b.ToTable("FundProfiles", (string)null);
                });

            modelBuilder.Entity("Backend.API.Domain.FundData.Models.FundHistoryRecord", b =>
                {
                    b.HasOne("Backend.API.Domain.FundData.Models.FundProfile", "FundProfile")
                        .WithMany("HistoryRecords")
                        .HasForeignKey("IsinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundProfile");
                });

            modelBuilder.Entity("Backend.API.Domain.FundData.Models.FundProfile", b =>
                {
                    b.Navigation("HistoryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
