using System.Diagnostics;

namespace Backend.API.Domain.FundData.ValueObjects;

/// <summary>
/// Strongly-typed identifier for <see cref="Models.FundHistoryRecord"/>.
/// </summary>
/// <remarks>
/// Uses a long value as the underlying identifier, auto-generated by the database.
/// </remarks>
[DebuggerDisplay("HistoryRecordId: {Value}")]
public readonly record struct FundHistoryRecordId(long Value) : IComparable<FundHistoryRecordId>
{
    /// <summary>
    /// Creates a new <see cref="FundHistoryRecordId"/> from the specified value.
    /// </summary>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when value is negative.</exception>
    public static FundHistoryRecordId Create(long value)
    {
        if (value < 0)
            throw new ArgumentOutOfRangeException(nameof(value), "Fund history record ID must be non-negative.");

        return new FundHistoryRecordId(value);
    }

    /// <summary>
    /// Creates a new <see cref="FundHistoryRecordId"/> for a new record (value = 0, to be assigned by database).
    /// </summary>
    public static FundHistoryRecordId New() => new(0);

    /// <inheritdoc />
    public int CompareTo(FundHistoryRecordId other) => Value.CompareTo(other.Value);

    /// <summary>
    /// Implicitly converts a <see cref="FundHistoryRecordId"/> to a <see cref="long"/>.
    /// </summary>
    public static implicit operator long(FundHistoryRecordId id) => id.Value;

    /// <inheritdoc />
    public override string ToString() => Value.ToString();
}
